#!/bin/sh

# Screen Layout in Case of Multi Monitor Setup Required
[ -f "$XDG_CONFIG_HOME"/X11/layout ] && . "$XDG_CONFIG_HOME"/X11/layout

slstatus &
xwallpaper --stretch "$WALLPAPER" &
picom &
xset s off
xset -dpms
setxkbmap -option caps:super
exec "$SESSION"
