#!/bin/sh

# Loading Pipewire if running linux
if [ "$KERNEL" = "Linux" ]; then
	# Shell daemons
	pipewire &
	pipewire-pulse &
fi

# Screen Layout in Case of Multi Monitor Setup Required
[ -f "$XDG_CONFIG_HOME"/X11/layout ] && . "$XDG_CONFIG_HOME"/X11/layout

slstatus &
xwallpaper --stretch "$WALLPAPER" &
picom --config "$XDG_CONFIG_HOME"/picom/picom.conf &
numlockx on &
lxsession &
xset s off
xset -dpms
wireplumber &
setxkbmap -option caps:super
exec "$SESSION"
