#!/bin/sh

#This is a script to turn on bluelight filter

#Detect if Redshift Already Running
running=$(ps -C redshift | grep redshift | awk '{print $4}')

if [ "$running" == "redshift" ]; then
			killall redshift
else
#Latitude Grab| Grabbing IP          | getting information from iplocation                  |qery| Grab latitude | grabbing the #   | removing "   | removing ,
	latitude=$(curl https://ipinfo.io/ip | xargs -I {} curl -s --get https://ipvigilante.com/{} | jq | grep latitude | awk '{print $2}' | sed s:'"'::g | sed s:','::g) &&
#Longitude Grab| Grabbing IP          | getting information from iplocation                  |qery| Grab longitude | grabbing the #   | removing "   | removing ,
	longitude=$(curl https://ipinfo.io/ip | xargs -I {} curl -s --get https://ipvigilante.com/{} | jq | grep longitude | awk '{print $2}' | sed s:'"'::g | sed s:','::g) &&
#Turning on Redshift with local coordinates
	redshift -l $latitude:$longitude -m randr
fi
