#!/bin/bash

#Deletes unrequired files/folders

#Deleting these files/folders and uneeded packages/dependencies
echo 'Cleaning up...'
yay --noconfirm -Sc >/dev/null
rm -rf $HOME/.cache \
	$HOME/.bash_history \
	$HOME/.wget* \
	$HOME/.Xsession-erro* \
	$HOME/.local/share/nautilus \
	$HOME/.local/share/qutebrowser \
	$HOME/.viminfo
yay -Rns $(pacman -Qtdq) 2>/dev/null >/dev/null
