#!/bin/bash

# A quick drive format utility

#Listing Drives        |Grabbing 1st char | Remove header | Add /dev/ to ^  |Output a menu of 20
formatdrive=$(lsblk -l | awk '{print $1}' | grep -vi NAME | sed s:^:/dev/:g | dmenu -i -p "Format:" -l 20)

#Listing partition types               | Outputs a list of 20
formatype=$(printf 'ext4\nfat32\nntfs' | dmenu -i -p "Type:" -l 20)

# Compairing the values of $formatype and $formatdrive and running it's desired formatation
if [ $formatype == ext4 ]; then
			sudo mkfs.ext4 $formatdrive
elif [ $formatype == fat32 ]; then
			sudo mkfs.vfat $formatdrive
elif [ $formatype == ntfs ]; then
			sudo mkfs.ntfs $formatdrive
else
			break
fi
