#!/bin/bash

#A script who mounts partitions through the dmenu

#Lists Partitions      | Grabs drive #    | Removes header| Adds /dev/ line | Outputs a Menu of 20
mountdevice=$(lsblk -l | awk '{print $1}' | grep -vi NAME | sed s:^:/dev/:g | dmenu -i -p "Mount:" -l 20)

#Lists Mountpoints                      | Outputs a Menu of 20            | Grabs the PATH   | Replaces ~ PATH with /HOME...
mountpoint=$(cat $HOME/.config/mounterc | dmenu -i -p "Mountpoint:" -l 20 | awk '{print $2}' | sed s:"~":/home/"$(whoami)":g)

#Mounts Partition to Mountpoint
sudo mount $mountdevice $mountpoint
