#!/bin/sh

#A quick open menu who lets you open any file from any part of your home directory with its default application

#Lists Directorys	       | Outputs menu 20| Grabs PATH	   | Replaces ~ with complete PATH | Lists files in the directory  | Replace complete PATH with ~  | Outputs menu 20| Replace ~ with complete PATH  | Opens with default app
cat $HOME/.config/directorysrc | dmenu -i -l 20 | awk '{print $2}' | sed s:"~":/home/"$(whoami)":g | xargs -I {} find "{}" -type f | sed s:/home/"$(whoami)":"~":g | dmenu -i -l 20 | sed s:"~":/home/"$(whoami)":g | xargs -I {} xdg-open "{}"
