#!/bin/bash

#A script who loads markdown documents and the compiles them into a pdf

curdir=$(pwd)
cd $HOME/Documents/Markdown

#Lists files inside Markdown| gets md | Outputs menu   | Compiles the Markdown Document into PDF and sends it to PDF Folder| Go back to initial folder
ls | grep md | dmenu -i -p "File to compile into PDF:" | xargs -I {} R -e "rmarkdown::render('"'{}'"', '"'pdf_document'"')" && mv *.pdf $HOME/Documents/PDF/ && cd $curdir
