#!/bin/bash

#A script who loads markdown documents and the compiles them into a pdf

#Lists files inside Markdown| gets md | Outputs menu 20| Compiles the Markdown Document into PDF and sends it to PDF Folder 
ls $HOME/Documents/Markdown | grep md | dmenu -i -l 20 | xargs -I {} R -e "rmarkdown::render('"'{}'"', '"'pdf_document'"')" && mv *.pdf $HOME/Documents/PDF/
