#!/bin/bash

#A menu which gives you the option to unmount drives from their desired folders

#Lists Mounted Devices  | Gets ^ w/dev| Prints partition#| Outputs Menu of 20
umountdevice=$(mount -l | grep ^/dev/ | awk '{print $1}' | dmenu -i -p "Umount:")

#Lists Mounted Folder         | Gets the location| Unmounts the Drive from location
mount -l | grep $umountdevice | awk '{print $3}' | xargs -I {} sudo umount {}
