#!/bin/bash

#A internal network scanner which lists active IP's inside of an internal network

#Scans internal network      | Shows Report| Prints IP's Hostname| Improves Visibilit| Removes )
sudo nmap -sP 192.168.1.1/24 | grep report | awk '{print $5 $6}' | sed s:'(':"-->":g | sed s:')'::g
