#!bin/sh

alias grep='grep -i' \
	clone='git clone' \
	add='git add' \
	stat='git status' \
	check='git checkout' \
	commit='git commit -m' \
	revert='git revert' \
	cherry='git cherry-pick' \
	push='git remote | xargs -L1 git push --all' \
	ytmp3='yt-dlp -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0' \
	ytmp4='yt-dlp -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"' \
	patchd='patch -p1 <' \
	mkdiff='diff -u' \
	clip='xclip -selection clipboard' \
	trim='convert -trim' \
	trans='convert -transparent -fuzz' \
	x='7z x' \
	e='$EDITOR' \
	g='$IMAGE -t *' \
	fm='$FILE' \
	dl='curl -LO' \
	m='udisksctl mount -b' \
	u='udisksctl unmount -b' \
	pyenv='python -m venv $PYENV && . "$PYENV"/bin/activate'
