#!/bin/sh

###################
# Setting Up Vars #
###################

SRC=$(pwd)
KERNEL=$(uname)

#################################
# Cloning and Cleaning Programs #
#################################

git clone https://github.com/rafa-99/dmenu.git
git clone https://github.com/rafa-99/dwm.git
git clone https://github.com/rafa-99/st.git
git clone https://github.com/rafa-99/xmouseless.git

cd "$SRC"/dmenu && git pull ;
cd "$SRC"/dwm && git pull ;
cd "$SRC"/st && git pull ;
cd "$SRC"/xmouseless && git pull ;

##########################
# Setting Configurations #
##########################

[ ! -f "$SRC"/dmenu/config.h ] && cp -rf "$HOME"/.config/suckless/dmenu/config.h "$SRC"/dmenu/ ;
[ ! -f "$SRC"/dwm/config.h ] && cp -rf "$HOME"/.config/suckless/dwm/config.h "$SRC"/dwm/ ;
[ ! -f "$SRC"/st/config.h ] && cp -rf "$HOME"/.config/suckless/st/config.h "$SRC"/st/ ;
[ ! -f "$SRC"/xmouseless/config.h ] && cp -rf "$HOME"/.config/suckless/xmouseless/config.h "$SRC"/xmouseless/ ;

########################
# Recompiling Programs #
########################

cd "$SRC"/dwm && git pull ; sudo make clean install ; make clean
cd "$SRC"/dmenu && git pull ; sudo make clean install ; make clean
cd "$SRC"/st && git pull ; sudo make clean install ; make clean
cd "$SRC"/xmouseless && git pull ; sudo make clean install ; make clean
