---
- name: Setup and configure the user's environment with dotfiles
  hosts: localhost
  connection: local

  vars:
    # List of packages to install
    packages:
      - neovim

    # List of custom directories to create under user's home directory
    custom_directories:
      - Documents/PDF
      - Documents/Text
      - Documents/Disks
      - Documents/Archives
      - Documents/VMs
      - Pictures/Screenshots
      - Pictures/GIMP
      - Videos/Recordings
      - Code
      - .config/git
      - .config/wallpaper

    # List of files to create under ~/.config/mpd/ and other directories
    touch_files:
      - .config/mpd/database
      - .config/mpd/log
      - .config/mpd/pid
      - .config/mpd/state
      - .config/mpd/sticker.sql

  tasks:

    # Update Firmware
    - name: Update system's software
      shell: fw_update
      become: true

    # Patch System Firmware
    - name: Applies system patches
      shell: syspatch
      become: true

    # Install necessary packages
    - name: Install necessary packages
      community.general.openbsd_pkg:
        name: "{{ packages }}"
        state: present
        autoremove: true
      become: true

    # Ensure necessary custom directories exist for user (run as user)
    - name: Ensure custom directories exist for user
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: directory
        mode: '0755'
      with_items: "{{ custom_directories }}"

    # Deploy dotfiles using stow (run as user)
    - name: Deploy dotfiles using stow
      shell: stow -t {{ ansible_env.HOME }} {{ dotfiles_dirs | join(' ') }}

    # Ensure specified files are created (touch them if they do not exist)
    - name: Ensure specified files are created
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: touch
        mode: '0644'
      with_items: "{{ touch_files }}"

    # Set zsh as default shell for user (run as user)
    - name: Set zsh as default shell for user
      shell: chsh -s /usr/bin/zsh {{ ansible_env.USER }}
      become: true  # Use root to install these packages

    # Configure git-lfs for user (run as user)
    - name: Configure git-lfs for user
      command: git lfs install

    # Git configuration task
    - name: Configure git user and email for user
      shell: |
        git config --global user.name "{{ git_user }}"
        git config --global user.email "{{ git_email }}"
        git config --global pull.rebase false
        mv {{ ansible_env.HOME }}/.gitconfig {{ ansible_env.HOME }}/.config/git/config

    # Run the compileSource script from ~/.local/src (requires root permissions)
    - name: Run compileSource script from ~/.local/src
      shell: "{{ ansible_env.HOME }}/.local/src/compileSource"
      args:
        chdir: "{{ ansible_env.HOME }}/.local/src"  # Make sure to run the script from the correct directory

    # Remove unnecessary files
    - name: Remove unnecessary files
      file:
        path: "{{ ansible_env.HOME }}/{{ item }}"
        state: absent
      with_items: "{{ remove_files }}"

    # Reboot Schedule
    - name: Schedule reboot in 5 seconds
      shell: "sleep 5 && reboot"
      async: 1
      poll: 0
      become: true
