#!/bin/sh

echo "######################"
echo "# dotfiles Installer #"
echo "######################"
echo "|   for Arch Linux   |"
echo "**********************"

# Setting Vars
CURDIR=$(pwd)

# Installing Deps
sudo pacman --needed -S zsh zsh-syntax-highlighting youtube-dl engrampa nmap geany base-devel vim ncmpcpp mpd mpc xcompmgr xwallpaper xclip newsboat vifm zathura r qutebrowser tcl tk mpv libpng libjpeg-turbo webkit2gtk gtk2 gtk3 gtkmm gtkmm3 wxgtk-common wxgtk3 grc gst-libav gst-plugins-good maim ntfs-3g ffmpeg acpi transset-df texlive-most pcmanfm lxappearance arc-gtk-theme papirus-icon-theme

# Disabling having to type password to yse sudo command
printf "Sudo mode you want to use:\n1. Safe Mode (Commands Password Locked)\n2. Unprotected (No password required when running sudo commands)\n-> " && Read SUMODE
######################################
if [ $SUMODE == 1 ]; then
		sudo echo >>/etc/sudoers && sudo echo '## Programs to run without sudo password'>>/etc/sudoers && sudo echo 'ALL ALL=NOPASSWD: /bin/mount, \' && sudo echo '		/bin/umount, \'>>/etc/sudoers && sudo echo '		/bin/mkfs.ext4, \'>>/etc/sudoers && sudo echo '		/bin/mkfs.vfat, \'>>/etc/sudoers && sudo echo '		/bin/mkfs.ntfs'>>/etc/sudoers
######################################
elif [ $SUMODE == 2 ]; then
		sudo sed -i s/'# %wheel ALL=(ALL) NOPASSWD: ALL'/'%wheel ALL=(ALL) NOPASSWD: ALL'/g /etc/sudoers
######################################
else
		sudo echo >>/etc/sudoers && sudo echo '## Programs to run without sudo password'>>/etc/sudoers && sudo echo 'ALL ALL=NOPASSWD: /bin/mount, \' && sudo echo '		/bin/umount, \'>>/etc/sudoers && sudo echo '		/bin/mkfs.ext4, \'>>/etc/sudoers && sudo echo '		/bin/mkfs.vfat, \'>>/etc/sudoers && sudo echo '		/bin/mkfs.ntfs'>>/etc/sudoers
######################################
fi

#Preparing Dirs and Files for dotfiles
cp -rf .* $HOME
cp -rf Pictures/ $HOME/
rm -rf $HOME/.git \
	$HOME/LICENSE \
	$HOME/install \
	$HOME/logo.png \
	$HOME/README.md
xrdb $HOME/.Xresources
mkdir -p ~/Mount
mkdir -p ~/Mount/Drive
mkdir -p ~/Mount/Drive2
mkdir -p ~/Mount/Drive3
mkdir -p ~/Mount/MTP
mkdir -p ~/Mount/USB
mkdir -p ~/Mount/USB2
mkdir -p ~/Mount/USB3
mkdir -p ~/Documents/PDF
mkdir -p ~/Documents/Markdown
mkdir -p ~/Documents/Groff
mkdir -p ~/Documents/Disks
mkdir -p ~/Documents/Archives
mkdir -p ~/Documents/Word
mkdir -p ~/Documents/Powerpoint
mkdir -p ~/Documents/Excel
mkdir -p ~/Repositories
mkdir -p ~/Pictures/Screenshots
mkdir -p ~/Pictures/GIMP
mkdir -p ~/Videos/Recordings

### Install of Suckless tools
mkdir suck
cd suck && git clone https://gitlab.com/rafa_99/dmenu && \
	git clone https://gitlab.com/rafa_99/st && \
	git clone https://gitlab.com/rafa_99/surf && \
	git clone https://gitlab.com/rafa_99/tabbed && \
	git clone https://gitlab.com/rafa_99/farbfeld && \
	git clone https://gitlab.com/rafa_99/sent && \
	git clone https://gitlab.com/rafa_99/slock
cd $CURDIR/suck/dmenu && sudo make clean install
cd $CURDIR/suck/st && sudo make clean install
cd $CURDIR/suck/surf && sudo make clean install
cd $CURDIR/suck/tabbed && sudo make clean install
cd $CURDIR/suck/farbfeld && sudo make clean install
cd $CURDIR/suck/sent && sudo make clean install
cd $CURDIR/suck/slock && sudo make clean install
cd $CURDIR && sudo rm -rf suck/

# Changing default shell to zsh
chsh -s /bin/zsh
