#!/bin/sh

echo "######################"
echo "# dotfiles Installer #"
echo "######################"
echo "|   for Arch Linux   |"
echo "**********************"

# Setting Vars
CURDIR=$(pwd)

# Installing Deps
sudo pacman --needed -S brightnessctl zsh zsh-syntax-highlighting youtube-dl engrampa nmap geany base-devel vim ncmpcpp mpd mpc xwallpaper xclip newsboat vifm zathura r qutebrowser tcl tk mpv libpng libjpeg-turbo webkit2gtk gtk2 gtk3 gtkmm gtkmm3 wxgtk-common wxgtk3 grc gst-libav gst-plugins-good maim ntfs-3g ffmpeg acpi transset-df texlive-most pcmanfm lxappearance arc-gtk-theme papirus-icon-theme

# Updated sudo permissions
sudo cp -rf sudoers /etc/sudoers

#Preparing Dirs and Files for dotfiles
cp -rf .* $HOME
cp -rf Pictures/ $HOME/
rm -rf $HOME/.git \
	$HOME/LICENSE \
	$HOME/install \
	$HOME/logo.png \
	$HOME/README.md \
	$HOME/sudoers
xrdb $HOME/.Xresources
mkdir -p ~/Mount
mkdir -p ~/Mount/Drive
mkdir -p ~/Mount/Drive2
mkdir -p ~/Mount/Drive3
mkdir -p ~/Mount/MTP
mkdir -p ~/Mount/USB
mkdir -p ~/Mount/USB2
mkdir -p ~/Mount/USB3
mkdir -p ~/Documents/PDF
mkdir -p ~/Documents/Markdown
mkdir -p ~/Documents/Groff
mkdir -p ~/Documents/Disks
mkdir -p ~/Documents/Archives
mkdir -p ~/Documents/Word
mkdir -p ~/Documents/Powerpoint
mkdir -p ~/Documents/Excel
mkdir -p ~/Repositories
mkdir -p ~/Pictures/Screenshots
mkdir -p ~/Pictures/GIMP
mkdir -p ~/Videos/Recordings

### Install of Suckless tools
mkdir suck
cd suck && git clone https://gitlab.com/rafa_99/dmenu && \
	git clone https://gitlab.com/rafa_99/st && \
	git clone https://gitlab.com/rafa_99/surf && \
	git clone https://gitlab.com/rafa_99/tabbed && \
	git clone https://gitlab.com/rafa_99/farbfeld && \
	git clone https://gitlab.com/rafa_99/sent && \
	git clone https://gitlab.com/rafa_99/slock
cd $CURDIR/suck/dmenu && sudo make clean install
cd $CURDIR/suck/st && sudo make clean install
cd $CURDIR/suck/surf && sudo make clean install
cd $CURDIR/suck/tabbed && sudo make clean install
cd $CURDIR/suck/farbfeld && sudo make clean install
cd $CURDIR/suck/sent && sudo make clean install
cd $CURDIR/suck/slock && sudo make clean install
cd $CURDIR && sudo rm -rf suck/

# Changing default shell to zsh
chsh -s /bin/zsh

# Diferenciating from laptop to desktop
echo "Are you running a laptop or a desktop?" && printf "1)Laptop\n2)Desktop\nWhich type of computer you're running?:" && read PC && clear
sleep 1

if [ $PC == 1 ]; then
		sed -i s:custom:laptop:g ~/.config/polybar/config
elif [ $PC == 2 ]; then
		sed -i s:custom:desktop:g ~/.config/polybar/config
else
		echo "Skipping..."
fi

# Compositor Selection
echo "Which compositor you want to run?" && printf "1)xcompmgr\n2)compton\n ->" && read Compositor && clear
sleep 1

if [ $Compositor == 1 ]; then
		sudo pacman -S xcompmgr && sed -i s:compositor:xcompmgr:g ~/.config/bspwm/bspwmrc && sed -i s:compositor:xcompmgr:g ~/.config/dwm/autostart && sed -i s:compositor:xcompmgr:g ~/.config/i3/config && sed -i s:compositor:xcompmgr:g ~/.config/polybar/autostart

elif [ $Compositor == 2 ]; then
		sudo pacman -S compton && sed -i s:compositor:compton:g ~/.config/bspwm/bspwmrc && sed -i s:compositor:compton:g ~/.config/dwm/autostart && sed -i s:compositor:compton:g ~/.config/i3/config && sed -i s:compositor:compton:g ~/.config/openbox/autostart

else
		echo "Skipping..."
fi
