#!/bin/sh

echo "######################"
echo "# Packages Installer #"
echo "######################"
echo "|  for Gentoo Linux  |"
echo "**********************"

# Setting Vars
CURDIR=$(pwd)

# Distributing Configs for Portage
doas cp -rf ".local/etc/" "/etc/"

# Installing Deps
emerge --ask playonlinux lutris engrampa youtube-dl nmap ncmpcpp media-sound/mpc nitrogen x11-misc/xclip vifm zathura zathura-pdf-poppler mpv tk scrot ntfs3g pcmanfm lxappearance filezilla redshift numlockx neofetch htop transmission R pandoc-citeproc zip wget make bc android-tools unar arandr shellcheck gimp xorg-x11 xinit zsh webkit-gtk alsa-tools alsa-utils alsa-firmware alsa-plugins alsa-lib flaggie acpi lm-sensors media-sound/mpd app-admin/system-config-printer app-portage/layman dev-java/openjdk-bin geany x11-themes/papirus-icon-theme x11-themes/arc-theme nm-applet media-plugins/gst-plugins-libav sxiv texlive firefox kdenlive pm-utils doas 
