#!/bin/sh

echo "######################"
echo "# dotfiles Installer #"
echo "######################"
echo "|  for Gentoo Linux  |"
echo "**********************"

# Setting Vars
CURDIR=$(pwd)

# Distributing Configs for Portage
sudo cp -rf ".local/etc/" "/etc/"

# Installing Deps
emerge --ask playonlinux lutris engrampa youtube-dl nmap ncmpcpp media-sound/mpc nitrogen x11-misc/xclip vifm zathura zathura-pdf-poppler mpv tk scrot ntfs3g pcmanfm lxappearance filezilla redshift numlockx neofetch htop transmission-remote-gtk R pandoc-citeproc zip wget make bc android-tools unar arandr shellcheck gimp xorg-x11 xinit zsh webkit-gtk alsa-tools alsa-utils alsa-firmware alsa-plugins alsa-lib flaggie acpi lm-sensors media-sound/mpd app-admin/system-config-printer app-portage/layman dev-java/openjdk-bin geany x11-themes/papirus-icon-theme x11-themes/arc-theme nm-applet media-plugins/gst-plugins-libav sxiv texlive firefox kdenlive

# Setting up rootless Xorg Server
usermod -aG audio "$(whoami)"

#Preparing Dirs and Files for dotfiles
cp -rf .* "$HOME"
rm -rf "$HOME"/.git \
	"$HOME"/LICENSE \
	"$HOME"/install \
	"$HOME"/logo.png \
	"$HOME"/README.md \
	"$HOME"/.local/etc
mkdir -p ~/Mount
mkdir -p ~/Mount/Drive
mkdir -p ~/Mount/Drive2
mkdir -p ~/Mount/Drive3
mkdir -p ~/Mount/MTP
mkdir -p ~/Mount/USB
mkdir -p ~/Mount/USB2
mkdir -p ~/Mount/USB3
mkdir -p ~/Documents/PDF
mkdir -p ~/Documents/Markdown
mkdir -p ~/Documents/Groff
mkdir -p ~/Documents/Java
mkdir -p ~/Documents/Disks
mkdir -p ~/Documents/Archives
mkdir -p ~/Documents/Word
mkdir -p ~/Documents/Powerpoint
mkdir -p ~/Documents/Excel
mkdir -p ~/Repositories
mkdir -p ~/Pictures/Screenshots
mkdir -p ~/Pictures/GIMP
mkdir -p ~/Videos/Recordings

### Install of Suckless tools
mkdir suck
cd suck && git clone https://gitlab.com/rafa_99/dwm -b gentoo && \
	git clone https://gitlab.com/rafa_99/dmenu && \
	git clone https://gitlab.com/rafa_99/st && \
	git clone https://gitlab.com/rafa_99/surf && \
	git clone https://gitlab.com/rafa_99/tabbed && \
	git clone https://gitlab.com/rafa_99/farbfeld && \
	git clone https://gitlab.com/rafa_99/sent && \
	git clone https://gitlab.com/rafa_99/slock
cd "$CURDIR"/suck/dwm && sudo make clean install
cd "$CURDIR"/suck/dmenu && sudo make clean install
cd "$CURDIR"/suck/st && sudo make clean install
cd "$CURDIR"/suck/surf && sudo make clean install
cd "$CURDIR"/suck/tabbed && sudo make clean install
cd "$CURDIR"/suck/farbfeld && sudo make clean install
cd "$CURDIR"/suck/sent && sudo make clean install
cd "$CURDIR"/suck/slock && sudo make clean install
cd "$CURDIR" && sudo rm -rf suck/

# Changing default shell to zsh
chsh -s /bin/zsh

# Sudo Mods
# sudo echo "export _JAVA_AWT_WM_NONREPARENTING=1" >>/etc/profile.d/jre.sh

# Block Junk Traffic on Your Computer
printf "Do you want to block junky traffic. Ads, tracking, porn, junk? [Y/n]" && read -r Junk && clear
if [ "$Junk" = "Y" ] || [ "$Junk" = "y" ]; then
		sudo cp -rf .local/etc/hosts /etc/
fi

# Setting up Neovim
## Linking Neovim to Vim
ln -s /usr/bin/nvim ~/.local/bin/vim 

## Installing Neovim Plugin Manager (Vim Plug)
curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

## Installing Plugins
nvim -c PlugInstall

## Installing Spell Checker
nvim -c setlocal spell spelllang=pt_pt
