#!/bin/bash

echo "######################"
echo "# dotfiles Installer #"
echo "######################"
echo "    for Arch Linux    "
echo "**********************"

sudo pacman --needed -S youtube-dl engrampa nmap geany base-devel vim ncmpcpp mpd mpc xcompmgr xwallpaper xclip newsboat vifm zathura r qutebrowser tcl tk mpv libpng libjpeg-turbo webkit2gtk gtk2 gtk3 gtkmm gtkmm3 wxgtk-common wxgtk3 grc gst-libav gst-plugins-good maim ntfs-3g ffmpeg
sudo sed -i s/'# %wheel ALL=(ALL) NOPASSWD: ALL'/'%wheel ALL=(ALL) NOPASSWD: ALL'/g /etc/sudoers
cp -rf .* $HOME
cp -rf Pictures/* $HOME/Pictures/
rm -rf $HOME/.git
rm -rf $HOME/LICENSE \
	$HOME/install \
	$HOME/logo.png
xrdb $HOME/.Xresources
mkdir -p ~/Mount
mkdir -p ~/Mount/Drive
mkdir -p ~/Mount/Drive2
mkdir -p ~/Mount/Drive3
mkdir -p ~/Mount/MTP
mkdir -p ~/Mount/USB
mkdir -p ~/Mount/USB2
mkdir -p ~/Mount/USB3
mkdir -p ~/Documents/PDF
mkdir -p ~/Documents/Markdown
mkdir -p ~/Documents/Disks
mkdir -p ~/Documents/Archives
mkdir -p ~/Documents/Word
mkdir -p ~/Documents/Powerpoint
mkdir -p ~/Documents/Excel
mkdir -p ~/Repositories
mkdir -p ~/Pictures/Screenshots
mkdir -p ~/Pictures/GIMP
mkdir -p ~/Videos/Recordings

### Install of Suckless tools

CURDIR=$(pwd)
mkdir suck
cd suck && git clone https://gitlab.com/rafa_99/dwm && \
	git clone https://gitlab.com/rafa_99/dmenu && \
	git clone https://gitlab.com/rafa_99/st && \
	git clone https://gitlab.com/rafa_99/surf && \
	git clone https://gitlab.com/rafa_99/tabbed && \
	git clone https://gitlab.com/rafa_99/farbfeld && \
	git clone https://gitlab.com/rafa_99/sent && \
	git clone https://gitlab.com/rafa_99/slock
cd $CURDIR/suck/dwm && sudo make clean install
cd $CURDIR/suck/dmenu && sudo make clean install
cd $CURDIR/suck/st && sudo make clean install
cd $CURDIR/suck/surf && sudo make clean install
cd $CURDIR/suck/tabbed && sudo make clean install
cd $CURDIR/suck/farbfeld && sudo make clean install
cd $CURDIR/suck/sent && sudo make clean install
cd $CURDIR/suck/slock && sudo make clean install
cd $CURDIR && sudo rm -rf suck/
