#!/bin/sh

# setup Git account
printf "Do yo want to setup Git account? [Y/n]" && read -r GIT
if [ "$GIT" != "N" ] && [ "$GIT" != "n" ]; then
	printf "Username: " && read -r USER
	printf "Email: " && read -r EMAIL
	git config --global user.name "$USER"
	git config --global user.email "$EMAIL"
fi

# Setup atom
printf "Do yo want to install Atom packages? [Y/n]" && read -r ATOM
if [ "$ATOM" != "N" ] && [ "$ATOM" != "n" ]; then
apm install atom-beautify file-icons pigments teletype atom-doxit highlight-selected platformio-ide-terminal vim-mode-plus busy-signal intentions linter linter-ui-default linter-shellcheck
fi

# Setup flathub
printf "Do yo want to install flatpak packages? [Y/n]" && read -r FLAT
if [ "$FLAT" != "N" ] && [ "$FLAT" != "n" ]; then
	pkg i flatpak
	sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
fi
