#!/bin/sh

echo "######################"
echo "# Packages Installer #"
echo "######################"
echo "|  for Gentoo Linux  |"
echo "**********************"
echo

# Checking if is root
if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root" 1>&2
	exit 1
fi


printf "Do you want to install Extra Packages? [Y/n]" && read -r BASE
if [ "$BASE" != "N" ] && [ "$BASE" != "n" ]; then
	emerge --ask --quiet xwallpaper x11-misc/xclip vifm zathura zathura-pdf-poppler mpv zip wget make bc unar xorg-x11 xinit zsh webkit-gtk media-plugins/gst-plugins-libav sxiv pm-utils doas sys-fs/dosfstools app-editors/neovim alsa-lib alsa-plugins
fi

printf "Do you want to install Extra Packages? [Y/n]" && read -r EXTRA
if [ "$EXTRA" != "N" ] && [ "$EXTRA" != "n" ]; then
	emerge --ask --quiet youtube-dl ncmpcpp mpc mpd tk scrot ntfs3g lxappearance redshift numlockx transmission R pandoc-citeproc android-tools shellcheck app-admin/system-config-printer papirus-icon-theme arc-theme texlive net-libs/nodejs mail-client/neomutt net-mail/isync firefox libreoffice-bin unoconv dev-util/ctags gimp imagemagick lsd
fi
