#!/bin/sh

echo "######################"
echo "# dotfiles Installer #"
echo "######################"
echo "|  for Gentoo Linux  |"
echo "**********************"

# Setting Vars
CURDIR=$(pwd)

# Distributing Configs for Portage
sudo cp -rf ".local/etc/" "/etc/"

# Installing Deps
emerge --ask playonlinux lutris engrampa youtube-dl nmap ncmpcpp media-sound/mpc nitrogen x11-misc/xclip vifm zathura zathura-pdf-poppler mpv tk scrot ntfs3g pcmanfm lxappearance filezilla redshift numlockx neofetch htop transmission-remote-gtk R pandoc-citeproc zip wget make bc android-tools unar arandr shellcheck gimp firefox-bin xorg-11 xinit zsh webkit-gtk alsa-tools alsa-utils alsa-firmware alsa-plugins alsa-lib flaggie

# Added to Input Group
groupadd input

echo "Paste or Write this command on your Console "SUBSYSTEM=="input", ACTION=="add", GROUP="input""

echo "SUBSYSTEM=="input", ACTION=="add", GROUP="input"" | xclip --selection clipboard
