.TH  "DOTS" "1" "August 2021" "LINUX" "User Manual"
.SH KEYBINDS
.TP
\fBMODKEY \fR
windows key
.TP
\fBMODKEY \fR+ \fBJ\fR
navigate down the stack
.TP
\fBMODKEY \fR+ \fBK\fR
navigate up the stack
.TP
\fBMODKEY \fR+ \fBCTRL \fR+ \fBP\fR
promote window to master stack
.TP
\fBMODKEY \fR+ \fBCTRL \fR+ \fBD\fR
demote window from master stack
.TP
\fBMODKEY \fR+ \fBCTRL \fR+ \fBH\fR
decrease master stack width
.TP
\fBMODKEY \fR+ \fBCTRL \fR+ \fBL\fR
increase master stack width
.TP
\fBMODKEY \fR+ \fBTAB\fR
switch between last open tag
.TP
\fBMODKEY \fR+ \fBSPACE\fR
pop window to top of master stack
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBQ\fR
kill window
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBX\fR
kill window manager
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBR\fR
restart window manager
.TP
\fBMODKEY \fR+ \fB[UP\fB, DOWN\fB, LEFT\fB, RIGHT\fB]\fR
move floating window [up, down, left, right]
.TP
\fBMODKEY \fR+ \fBCTRL \fR+ \fB[UP\fB, DOWN\fB, LEFT\fB, RIGHT\fB]\fR
resize floating window
.TP
\fBMODKEY \fR+ \fBH\fR
switch to tag to the left
.TP
\fBMODKEY \fR+ \fBL\fR
switch to tag to the right
.TP
\fBMODKEY \fR+ \fBCOMMA\fR
switch to monitor to the left
.TP
\fBMODKEY \fR+ \fBPERIOD\fR
switch to monitor to the right
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBH\fR
send window to tag to the left
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBL\fR
send window to tag to the right
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBCOMMA\fR
send window to monitor to the left
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBPERIOD\fR
send window to monitor to the right
.TP
\fBMODKEY \fR+ \fBB\fR
toggle status bar
.TP
\fBMODKEY \fR+ \fB0\fR
view windows from all tags
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fB0\fR
make window visible on all tags
.TP
\fBMODKEY \fR+ \fB[1\fB-9\fB]\fR
view tag [1-9]
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fB[1\fB-9\fB]\fR
send window to tag [1-9]
.TP
\fBMODKEY \fR+ \fBALT \fR+ \fB[1\fB-7\fB]\fR
set a custom layout [1-7]
.TP
\fBMODKEY \fR+ \fBALT \fR+ \fBSPACE\fR
set window to floating
.TP
\fBMODKEY \fR+ \fBD\fR
open dmenu prompt
.TP
\fBMODKEY \fR+ \fBRETURN\fR
open terminal
.TP
\fBMODKEY \fR+ \fBW\fR
open web browser
.TP
\fBMODKEY \fR+ \fBF\fR
open file manager
.TP
\fBMODKEY \fR+ \fBN\fR
open rss feed
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBD\fR
open dotfiles documentation
.TP
\fBMODKEY \fR+ \fBS\fR
open quick web search menu
.TP
\fBMODKEY \fR+ \fBE\fR
open emoji/glyphs menu
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBO\fR
open monitor output selector
.TP
\fBMODKEY \fR+ \fBM\fR
open music selector
.TP
\fBMODKEY \fR+ \fBC\fR
open power menu
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBF\fR
open flatpak list
.TP
\fBPRINT SCREEN\fR
open screenshot menu
.TP
\fBMODKEY \fR+ \fBPRINT SCREEN\fR
takes a quick screenshot
.TP
\fBMODKEY \fR+ \fBP\fR
open passwords menu prompt
.TP
\fBMODKEY \fR+ \fBSHIFT \fR+ \fBS\fR
displays screenkeys
.TP
\fBMODKEY \fR+ \fBV\fR
opens youtube video
.TP
\fBMODKEY \fR+ \fBF1\fR
toggles audio mute
.TP
\fBMODKEY \fR+ \fBF2\fR
decreases volume
.TP
\fBMODKEY \fR+ \fBF3\fR
increases volume
.TP
\fBMODKEY \fR+ \fBF4\fR
toggles microphone mute
.TP
\fBMODKEY \fR+ \fBF5\fR
decreases backlight intensity
.TP
\fBMODKEY \fR+ \fBF6\fR
increases backlight intensity
.TP
\fBMODKEY \fR+ \fBF7\fR
toggles bluelight filter
.TP
\fBMODKEY \fR+ \fBF8\fR
opens screerecord menu
.TP
\fBMODKEY \fR+ \fBF9\fR
pause/play music
.TP
\fBMODKEY \fR+ \fBF9\fR
pause/play music
.TP
\fBMODKEY \fR+ \fBF10\fR
stop music
.TP
\fBMODKEY \fR+ \fBF11\fR
skip previous track
.TP
\fBMODKEY \fR+ \fBF11\fR
skip next track

.SH ENVIRONMENT
.TP
\fBEDITOR\fR
default plain text editor
.TP
\fBTERMINAL\fR
default terminal program
.TP
\fBBROWSER\fR
default web browser
.TP
\fBREADER\fR
default pdf visualizer
.TP
\fBFILE\fR
default file manager
.TP
\fBNEWS\fR
default rss reader
.TP
\fBDOCS\fR
default documentation command
.TP
\fBSUCK\fR
default suckless configurations path
.TP
\fBPASSWORDS\fR
default passwords file path
.TP
\fBWALLPAPER\fR
default wallpaper path
.TP
\fBSESSION\fR
default graphical session

.SH AUTHOR
Written by Rafael Marçalo.
