#!/bin/sh

###################
# Setting Up Vars #
###################

SUCKLESS="$HOME/Repositories/Suckless"

#################################
# Cloning and Cleaning Programs #
#################################

cd "$SUCKLESS" && \
	git clone https://gitlab.com/rafa_99/dwm 2>/dev/null ; \
	git clone https://gitlab.com/rafa_99/dmenu 2>/dev/null ; \
	git clone https://gitlab.com/rafa_99/st 2>/dev/null ; \
	git clone https://gitlab.com/rafa_99/surf 2>/dev/null ; \
	git clone https://gitlab.com/rafa_99/tabbed 2>/dev/null ; \
	git clone https://gitlab.com/rafa_99/farbfeld 2>/dev/null ; \
	git clone https://gitlab.com/rafa_99/sent 2>/dev/null ; \
	git clone https://gitlab.com/rafa_99/slock 2>/dev/null
cd "$SUCKLESS"/dwm && git pull && git checkout . ;
cd "$SUCKLESS"/dmenu && git pull && git checkout . ;
cd "$SUCKLESS"/st && git pull && git checkout . ;
cd "$SUCKLESS"/surf && git pull && git checkout . ;
cd "$SUCKLESS"/tabbed && git pull && git checkout . ;
cd "$SUCKLESS"/farbfeld && git pull && git checkout . ;
cd "$SUCKLESS"/sent && git pull && git checkout . ;
cd "$SUCKLESS"/slock && git pull && git checkout .

##########################
# Selecting Color Scheme #
##########################

printf "Select a color scheme:\n1. Black and White\n2. Cyan\n3. Green\n4. Red\n5. Default Colors\n\n-> " && read -r SCHEME
case "$SCHEME" in
	1)
	cp -rf "$SUCKLESS"/colors/BW/* "$SUCKLESS" && mv -f "$SUCKLESS/wallpaper.png" "$HOME/.config/wallpaper/"
		;;
	2)
	cp -rf "$SUCKLESS"/colors/Cyan/* "$SUCKLESS" && mv -f "$SUCKLESS/wallpaper.png" "$HOME/.config/wallpaper/"
		;;
	3)
	cp -rf "$SUCKLESS"/colors/Green/* "$SUCKLESS" && mv -f "$SUCKLESS/wallpaper.png" "$HOME/.config/wallpaper/"
		;;
	4)
	cp -rf "$SUCKLESS"/colors/Red/* "$SUCKLESS" && mv -f "$SUCKLESS/wallpaper.png" "$HOME/.config/wallpaper/"
		;;
	*)
	rm -rf "$HOME/.config/wallpaper/wallpaper.png"
		;;
esac

########################
# Recompiling Programs #
########################

cd "$SUCKLESS"/dwm && git pull ; doas make clean install ; make clean
cd "$SUCKLESS"/dmenu && git pull ; doas make clean install ; make clean
cd "$SUCKLESS"/st && git pull ; doas make clean install ; make clean
cd "$SUCKLESS"/surf && git pull ; doas make clean install ; make clean
cd "$SUCKLESS"/tabbed && git pull ; doas make clean install ; make clean
cd "$SUCKLESS"/farbfeld && git pull ; doas make clean install ; make clean
cd "$SUCKLESS"/sent && git pull ; doas make clean install ; make clean
cd "$SUCKLESS"/slock && git pull ; doas make clean install ; make clean
