#!/bin/sh

###################
# Setting Up Vars #
###################

SUCK=$(pwd)

#################################
# Cloning and Cleaning Programs #
#################################

git clone https://gitlab.com/rafa_99/dwm
git clone https://gitlab.com/rafa_99/slstatus
git clone https://gitlab.com/rafa_99/dmenu
git clone https://gitlab.com/rafa_99/st
git clone https://gitlab.com/rafa_99/farbfeld
git clone https://gitlab.com/rafa_99/sent
git clone https://gitlab.com/rafa_99/slock
cd "$SUCK"/dwm && git pull && git checkout . ;
cd "$SUCK"/slstatus && git pull && git checkout . ;
cd "$SUCK"/dmenu && git pull && git checkout . ;
cd "$SUCK"/st && git pull && git checkout . ;
cd "$SUCK"/farbfeld && git pull && git checkout . ;
cd "$SUCK"/sent && git pull && git checkout . ;
cd "$SUCK"/slock && git pull && git checkout .

##########################
# Selecting Color Scheme #
##########################

printf "Select a color scheme:\n1. Black and White\n2. Cyan\n3. Green\n4. Red\n5. Wal\n6. Default Colors\n\n-> " && read -r SCHEME
case "$SCHEME" in
	1)
		cp -rf "$SUCK"/colors/BW/* "$SUCK" && mv -f "$SUCK"/wallpaper.png "$HOME"/.config/wallpaper/
		;;
	2)
		cp -rf "$SUCK"/colors/Cyan/* "$SUCK" && mv -f "$SUCK"/wallpaper.png "$HOME"/.config/wallpaper/
		;;
	3)
		cp -rf "$SUCK"/colors/Green/* "$SUCK" && mv -f "$SUCK"/wallpaper.png "$HOME"/.config/wallpaper/
		;;
	4)
		cp -rf "$SUCK"/colors/Red/* "$SUCK" && mv -f "$SUCK"/wallpaper.png "$HOME"/.config/wallpaper/
		;;
	5)
		cp -rf "$SUCK"/colors/Wal/* "$SUCK" && mv -f "$SUCK"/wallpaper.png "$HOME"/.config/wallpaper/
esac

########################
# Recompiling Programs #
########################

cd "$SUCK"/dwm && git pull ; doas make clean install ; make clean
cd "$SUCK"/slstatus && git pull ; doas make clean install ; make clean
cd "$SUCK"/dmenu && git pull ; doas make clean install ; make clean
cd "$SUCK"/st && git pull ; doas make clean install ; make clean
cd "$SUCK"/farbfeld && git pull ; doas make clean install ; make clean
cd "$SUCK"/sent && git pull ; doas make clean install ; make clean
cd "$SUCK"/slock && git pull ; doas make clean install ; make clean
