#!/bin/sh

###################
# Setting Up Vars #
###################

SUCK=$(pwd)

#################################
# Cloning and Cleaning Programs #
#################################

git clone https://gitlab.com/rafa_99/dmenu
git clone https://gitlab.com/rafa_99/dwm
git clone https://gitlab.com/rafa_99/farbfeld
git clone https://gitlab.com/rafa_99/neovimb
git clone https://gitlab.com/rafa_99/pkg
git clone https://gitlab.com/rafa_99/sent
git clone https://gitlab.com/rafa_99/slock
git clone https://gitlab.com/rafa_99/slstatus
git clone https://gitlab.com/rafa_99/st
git clone https://gitlab.com/rafa_99/tabbed
cd "$SUCK"/dmenu && git pull ;
cd "$SUCK"/dwm && git pull ;
cd "$SUCK"/farbfeld && git pull ;
cd "$SUCK"/neovimb && git pull ;
cd "$SUCK"/pkg && git pull ;
cd "$SUCK"/sent && git pull ;
cd "$SUCK"/slock && git pull ;
cd "$SUCK"/slstatus && git pull ;
cd "$SUCK"/st && git pull ;
cd "$SUCK"/tabbed && git pull

########################
# Recompiling Programs #
########################

cd "$SUCK"/dwm && git pull ; doas make clean install ; make clean
cd "$SUCK"/dmenu && git pull ; doas make clean install ; make clean
cd "$SUCK"/farbfeld && git pull ; doas make clean install ; make clean
cd "$SUCK"/neovimb && git pull ; doas make clean install ; make clean
cd "$SUCK"/pkg && git pull ; doas make clean install ; make clean
cd "$SUCK"/sent && git pull ; doas make clean install ; make clean
cd "$SUCK"/slock && git pull ; doas make clean install ; make clean
cd "$SUCK"/slstatus && git pull ; doas make clean install ; make clean
cd "$SUCK"/st && git pull ; doas make clean install ; make clean
cd "$SUCK"/tabbed && git pull ; doas make clean install ; make clean
