#!/bin/sh

# Base Email Information
printf "Enter your desired email\n-> " && read -r SETEMAIL
printf "Enter your real name\n-> " && read -r SETNAME
printf "Enter your desired IMAP Server\n-> " && read -r SETIMAPSERVER
printf "Enter your desired IMAP Server Port\n-> " && read -r SETIMAPPORT
printf "Enter your desired SMTP Server\n-> " && read -r SETSMTPSERVER
printf "Enter your desired SMTP Server Port\n-> " && read -r SETSMTPPORT
printf "Enter your mail Inbox box name\n-> " && read -r SETINBOX
printf "Enter your mail Sent email box name\n-> " && read -r SETSENT
printf "Enter your mail Trash box name\n-> " && read -r SETTRASH
printf "Enter your mail Drafts box name\n-> " && read -r SETDRAFTS

# Email password configuration and encryption for safety reasons
printf "Enter your email password (Will be encrypted on your system)\n-> " && read -r SETPASSWORD
echo "Generating GPG key to go on top of the mail password..."
gpg --full-gen-key

# Replacing variables
sed -i s/SETEMAIL/"$SETEMAIL"/g neomuttrc
sed -i s/SETEMAIL/"$SETEMAIL"/g ~/.config/mbsync/mbsyncrc
sed -i s/SETNAME/"$SETNAME"/g neomuttrc
sed -i s/SETIMAPSERVER/"$SETIMAPSERVER"/g neomuttrc
sed -i s/SETIMAPSERVER/"$SETIMAPSERVER"/g ~/.config/mbsync/mbsyncrc
sed -i s/SETIMAPPORT/"$SETIMAPPORT"/g neomuttrc
sed -i s/SETSMTPSERVER/"$SETSMTPSERVER"/g neomuttrc
sed -i s/SETSMTPPORT/"$SETSMTPPORT"/g neomuttrc
sed -i s/SETINBOX/"$SETINBOX"/g neomuttrc
sed -i s/SETINBOX/"$SETINBOX"/g ~/.config/mbsync/mbsyncrc
sed -i s/SETSENT/"$SETSENT"/g neomuttrc
sed -i s/SETTRASH/"$SETTRASH"/g neomuttrc
sed -i s/SETDRAFTS/"$SETDRAFTS"/g neomuttrc

# Selecting which type of email to use
printf "Do you want to use:\n1. Online Cloud Email\n2. Local Email\n-> " && read -r OPTION

if [ "$OPTION" = 1 ]; then
	sed -i s:"# set folder = \"imaps":"set folder = \"imaps":g neomuttrc
	sed -i s:"# source \"gpg":"source \"gpg":g neomuttrc
	echo "set imap_pass = \"$SETPASSWORD\"" > pwd
	gpg -r "$SETEMAIL" -e pwd
	rm -rf pwd ../mbsync
elif
	[ "$OPTION" = 2 ]; then
	printf "Enter an alias for your mail account\n-> " && read -r SETACCOUNT
	sed -i s/SETACCOUNT/"$SETACCOUNT"/g neomuttrc
	sed -i s/SETACCOUNT/"$SETACCOUNT"/g ~/.config/mbsync/mbsyncrc
	mkdir -p ~/Documents/Mail/"$SETACCOUNT"
	echo "$SETPASSWORD" > pwd
	gpg -r "$SETEMAIL" -e pwd
	mv pwd.gpg ../mbsync
	rm -rf pwd
	sed -i s:"# set folder = \"~/":"set folder = \"~/":g neomuttrc
	mbsync -c ~/.config/mbsync/mbsyncrc "$SETACCOUNT"
fi
