#!/bin/sh

#
# Gentoo dots install
#

cd .. || exit
CURDIR=$(pwd)

echo "######################"
echo "# dotfiles Installer #"
echo "######################"
echo "|    Gentoo Linux    |"
echo "**********************"

if [ "$(id -u)" = "0" ]; then
	cp -rf ROOT/doas/doas.conf /etc
	cp -rf ROOT/issue/issue /etc
	cp -rf ROOT/hosts/hosts /etc

	emerge --ask --quiet app-text/zathura-meta sys-fs/ntfs3g vifm make xinit zsh doas sys-fs/dosfstools app-editors/neovim pulsemixer pipewire wireplumber gentoolkit stow app-admin/pass app-arch/p7zip zathura zathura-pdf-poppler xwallpaper x11-misc/xclip sxiv mpv newsboat ncmpcpp media-sound/mpc mpd redshift android-tools net-libs/nodejs libreoffice-bin unoconv dev-util/ctags gimp imagemagick net-misc/ntp maim media-libs/gst-plugins-good media-plugins/gst-plugins-libav go sys-apps/net-tools app-emulation/libvirt app-emulation/qemu app-emulation/virt-manager neofetch dev-python/pip x11-themes/arc-theme x11-themes/papirus-icon-theme ffmpegthumbnailer x11-misc/screenkey net-misc/yt-dlp net-p2p/transmission x11-misc/picom media-gfx/simple-scan dev-python/lxml media-libs/vulkan-loader media-libs/vulkan-layers net-print/hplip net-print/cups app-crypt/swtpm xorg-server firefox arandr ueberzug pavucontrol keepassxc x11-apps/setxkbmap zeal htop net-vpn/tor noto-emoji noto-cjk

	# Adding System default init services
	# go to https://localhost:631/ to configure the printer or run hp-setup
	USER=$(getent passwd | cut -d: -f6 | grep ^\/home | cut -d/ -f3 | head -1)
	gpasswd -a "$USER" lp
	gpasswd -a "$USER" lpadmin
	gpasswd -a "$USER" dialout
	gpasswd -a "$USER" kvm
	rc-update add cupsd default
	rc-update add elogind boot

	poweroff
else
	{

		# Building Folder Structure
		mkdir -p ~/Documents/PDF ~/Documents/Text ~/Documents/Disks ~/Documents/Archives ~/Documents/VMs ~/Downloads ~/Games/WINEPREFIX ~/Pictures/Screenshots ~/Pictures/GIMP ~/Videos/Recordings ~/Code ~/.config/git ~/.config/wallpaper ~/.local/share/gnupg ~/.local/share/pass

		doas sh -c 'echo "export _JAVA_AWT_WM_NONREPARENTING=1" >>/etc/profile.d/jre.sh'
		chsh -s /bin/zsh

		# Deploy Dots
		stow --target="$HOME" fonts gtk keepass man misc mpd ncmpcpp newsboat neovim npm picom pipewire qt shell scripts suckless surf sxiv tor vifm X11 zathura zeal zsh
		touch ~/.config/X11/Xauthority ~/.config/mpd/database ~/.config/mpd/log ~/.config/mpd/pid  ~/.config/mpd/state ~/.config/mpd/sticker.sql

		cd ~/.local/src && sh compileSource && cd "$CURDIR" || exit

		# Setting up Neovim
		## Linking Neovim to Vim
		ln -s /usr/bin/nvim ~/.local/bin/vim

		## Installing Neovim Plugin Manager (Vim Plug)
		curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs \
			https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

		## Installing Plugins
		nvim -c PlugInstall

		# Setup Git account
		printf "Do yo want to setup Git account? [Y/n]" && read -r GIT
		if [ "$GIT" != "N" ] && [ "$GIT" != "n" ]; then
			printf "Username: " && read -r USER
			printf "Email: " && read -r EMAIL
			git config --global user.name "$USER"
			git config --global user.email "$EMAIL"
			git config pull.rebase false
			mv ~/.gitconfig ~/.config/git/config
			git config --global pull.rebase false
		fi
	}
fi
