#!bin/sh

alias ls='ls --color=auto' \
	grep='grep --color=auto -i' \
	xr='xrdb ~/.Xresources' \
	update='sudo emerge-webrsync && sudo emerge --update --deep --with-bdeps=y --newuse @world' \
	remove='sudo emerge -C' \
	install='sudo emerge --ask' \
	search='emerge --search' \
	cleanup='sudo emerge --depclean' \
	clone='git clone' \
	add='git add' \
	stat='git status' \
	check='git checkout' \
	commit='git commit -m' \
	revert='git revert' \
	cherry='git cherry-pick' \
	push='git push origin' \
	fonts='fc-cache -fv' \
	ytmp3='youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0' \
	ytmp4='youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"' \
	patch='patch -p1 <' \
	mkdiff='diff -u' \
	del='rm -rf' \
	copy='cp -rf' \
	encrypt='openssl aes-256-cbc -a -salt' \
	decrypt='openssl aes-256-cbc -d -a' \
	clip='xclip -selection clipboard' \
	webget='wget --no-clobber --convert-links --random-wait -r -p -E -e robots=off -U mozilla' \
	trim='convert -trim' \
	trans='convert -transparent -fuzz' \
	synclock='sudo ntpdate pt.pool.ntp.org && sudo date -s "+1 hour" && sudo hwclock --systohc' \
