#!bin/sh

alias ls='ls --color=auto' \
	unlock='sudo rm -rf /var-lib/pacman/db.lck' \
	xr='xrdb ~/.Xresources' \
	update='yay -Syu' \
	remove='yay -Rns' \
	install='yay -S' \
	search='yay -Ss' \
	clone='git clone' \
	add='git add' \
	stat='git status' \
	check='git checkout' \
	commit='git commit -m' \
	revert='git revert' \
	cherry='git cherry-pick' \
	push='git push origin' \
	fonts='fc-cache -fv' \
	ytmp3='youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0' \
	ytmp4='youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"' \
	fpatch='patch -p1 <' \
	mkdiff='diff -u' \
	del='rm -rf' \
	copy='cp -rf' \
	encrypt='openssl aes-256-cbc -a -salt' \
	decrypt='openssl aes-256-cbc -d -a' \
	clip='xclip -selection clipboard' \
	webget='wget --no-clobber --convert-links --random-wait -r -p -E -e robots=off -U mozilla' \
	trim='convert -trim' \
	trans='convert -transparent -fuzz' \
	mirrors='reflector --sort rate --save /etc/pacman.d/mirrorlist' \
	synclock='sudo ntpdate pt.pool.ntp.org && sudo date -s "+1 hour" && sudo hwclock --systohc'
