#!bin/sh

alias ls='ls --color=auto' \
	unlock='sudo rm -rf /var-lib/pacman/db.lck' \
	xr='xrdb ~/.Xresources' \
	update='sudo pacman -Syu' \
	updateaur='yay -Syu' \
	remove='yay -Rns' \
	cleanup='yay --noconfirm -Sc && bash $HOME/.config/scripts/cleanup && yay -Rns $(pacman -Qtdq)' \
	install='yay -S' \
	search='yay -Ss' \
	clone='git clone' \
	add='git add' \
	stat='git status' \
	check='git checkout' \
	commit='git commit -m' \
	revert='git revert' \
	cherry='git cherry-pick' \
	push='git push origin' \
	fonts='fc-cache -fv' \
	ytmp3='youtube-dl -f bestaudio --extract-audio --audio-format mp3 --audio-quality 0' \
	ytmp4='youtube-dl -f "bestvideo[ext=mp4]+bestaudio[ext=m4a]/mp4"' \
	patch='patch -p1 <' \
	mkdf='diff -u' \
	del='rm -rf' \
	copy='cp -rf' \
	encrypt='openssl aes-256-cbc -a -salt' \
	decrypt='openssl aes-256-cbc -d -a' \
	rcompile='bash $HOME/.config/scripts/rcompile' \
	clip='xclip -selection clipboard' \
	whoshere='bash $HOME/.config/scripts/whoshere'
