#! /bin/sh

xsetroot -cursor_name left_ptr &

bspc monitor -d 1 2 3 4 5 6 7 8 9 0

bspc config border_width         1
bspc config window_gap           5

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		"#396087"
bspc config focused_border_color	"#a2e9d0"
bspc config urgent_border_color 	"#c1355d"
bspc config presel_feedback_color	"#5e81ac"

bspc rule -a Zathura state=tiled
