#! /bin/sh

sxhkd &
xcompmgr &
setxkbmap pt &
numlockx on &
xwallpaper --stretch $HOME/Pictures/Cyan_Francisco.png &
polybar custom &
xsetroot -cursor_name left_ptr &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		"#396087"
bspc config focused_border_color	"#a2e9d0"
bspc config urgent_border_color 	"#c1355d"
bspc config presel_feedback_color	"#5e81ac"

bspc rule -a st state=tiled desktop=^1 follow=off
bspc rule -a qutebrowser state=tiled desktop=^2 follow=on
bspc rule -a surf state=tiled desktop=^2 follow=on
bspc rule -a tabbed state=tiled desktop=^2 follow=on
bspc rule -a Pcmanfm state=tiled desktop=^3 follow=on
bspc rule -a vifm state=tiled desktop=^3 follow=on
bspc rule -a Zathura state=tiled desktop=^4 follow=on
bspc rule -a Gimp state=tiled desktop=^8 follow=on
bspc rule -a Sxiv state=tiled desktop=^8 follow=on
bspc rule -a Transmission-gtk state=tiled desktop=^9 follow=on
