#! /bin/sh

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap          30

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config normal_border_color		"#396087"
bspc config focused_border_color	"#a2e9d0"
bspc config urgent_border_color 	"#c1355d"
bspc config presel_feedback_color	"#5e81ac"

bspc rule -a Zathura state=tiled
