#!/bin/bash

mountdevice=$(lsblk -l | awk '{print $1}' | grep -vi NAME | sed s:^:/dev/:g | dmenu -i -p "Mount:" -l 20)

mountpoint=$(cat $HOME/.config/mounterc | dmenu -i -p "Mountpoint:" -l 20 | awk '{print $2}' | sed s:"~":/home/"$(whoami)":g)

sudo mount $mountdevice $mountpoint
